### ISSUE TITLE
License

### ISSUE THREAD

**Issue by light** [sterglee/GroovyLab#1]
Hi,

Could you clarify under what terms this project is licensed? The original project hosted on https://code.google.com/p/jlabgroovy/ states that it is licensed under the New BSD License, so I'm assuming that this is still the case here, but could you put a LICENSE file somewhere in this repo so that it is clear?

Thanks.

**Comment by rerdavies** [comment]
Unfortunate This code is unusable except for private use, without knowing what license terms are.

There are 16 files with license notices, ranging from "BSD License"  (that's it, no text), to GPL/LGPL(the horror. the horror), plus a "beerware" license that may or may not be BSD-compatible.

For what it's worth, the original BSD license seems to be inaccurate since there is at least one GPL-licensed file in the project. In passing, GPL/LGPL licensing is a serious impediment for many developers. Would be nice if you could get rid of that.

The consistent analysis I've gotten from lawyers is that LGPL would be nice if the terms matched the stated intent in the preamble. But the terms are largely incomprehensible to lawyers (and me as well).Therefore do not use LGPLfiles ever.So getting rid of the LGPL would be nice too. And GPL is of course right out of the question for almost all professional developers.
